function m(c,a,b,d){c.i.na(c.ca,a,b,d)}function p(c,a,b,d){c.i.s?m(c,a,b,d):c.i.Lb()._OnMessageFromDOM({type:"event",component:c.ca,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.i.g(c.ca,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.Y=class{constructor(c,a){this.i=c;this.ca=a}Xa(){}};window.uc=class{constructor(){}};"use strict";class aa{constructor(c){this.da=c;this.Ha=!1;this.La=!0;this.ea=this.D=this.Ua=-1}}
function ba(c,a){const b=a.elementId,d=c.X(b,a),e=new aa(d);c.K.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.La=!!a.isVisible;var f=c.Aa(d);f.addEventListener("focus",()=>{v(c,"elem-focused",b)});f.addEventListener("blur",()=>{v(c,"elem-blurred",b)});f=a.htmlIndex;e.Ua=f;e.ea=a.htmlZIndex;c.P&&(a=c.i.ya(f),e.D=a,c.i.ma(a).appendChild(d))}function w(c,a,b){t(c,a,d=>{const e=x(c,d.elementId);return b(e,d)})}
function x(c,a){c=c.K.get(a);if(!c)throw Error(`no element with id ${a}`);return c.da}function v(c,a,b,d){d||(d={});d.elementId=b;m(c,a,d)}function y(c,a,b,d){d||(d={});d.elementId=b;p(c,a,d)}
window.M=class extends self.Y{constructor(c,a){super(c,a);this.K=new Map;this.P=!0;u(this,[["create",b=>ba(this,b)],["destroy",b=>{b=b.elementId;const d=x(this,b);this.P&&d.parentElement.removeChild(d);this.K.delete(b)}],["set-visible",b=>{if(this.P){var d=this.K.get(b.elementId),e=d.da;d.Ha?e.style.display=b.isVisible?"":"none":d.La=!!b.isVisible}}],["update-position",b=>{if(this.P){var d=this.K.get(b.elementId),e=d.da,f=this.i;e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+
"px";e.style.height=b.height+"px";var g=b.fontSize;null!==g&&(e.style.fontSize=g+"em");g=b.htmlIndex;d.Ua=g;g=f.ya(g);g!==d.D&&(e.remove(),f.ma(g).appendChild(e),d.D=g,f.Ea());b=b.htmlZIndex;b!==d.ea&&(d.ea=b,f.Ea());d.Ha||(d.Ha=!0,d.La&&(e.style.display=""))}}],["update-state",b=>{const d=x(this,b.elementId);this.B(d,b)}],["focus",b=>{const d=this.Aa(x(this,b.elementId));b.focus?d.focus():d.blur()}],["set-css-style",b=>{const d=x(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,
b):d.style[e]=b}],["set-attribute",b=>{x(this,b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{x(this,b.elementId).removeAttribute(b.name)}]]);w(this,"get-element",b=>b)}X(){throw Error("required override");}B(){throw Error("required override");}Aa(c){return c}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),z=/android/i.test(navigator.userAgent);let da=0;
function B(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.kc?new Promise(b=>{const d="c3_resolve_"+da;++da;self[d]=b;a.textContent=c.oc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ea(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let C=new Audio;
const fa={"audio/webm; codecs=opus":!!C.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!C.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!C.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!C.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!C.canPlayType("audio/mp4"),"audio/mpeg":!!C.canPlayType("audio/mpeg")};C=null;async function ha(c){c=await ia(c);return(new TextDecoder("utf-8")).decode(c)}
function ia(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ja=0;const ka=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");ka.push(c)};const la=new Set(["cordova","playable-ad","instant-games"]);let ma=!1;
window.A=class c{constructor(a){this.s=a.qc;this.ha=null;this.o="";this.T=a.nc;this.ka={};this.Na=this.V=null;this.R=[];this.L=null;this.qb=!0;this.l=[];this.Ra=[];this.Sa=!1;this.sb=()=>this.Jb();this.pb=!1;this.fa=null;this.S=-1;this.fc=()=>this.Ub();this.ia=new Set;this.Va=null;this.tb=[];this.h=a.ub;this.Ja="file"===location.protocol.substr(0,4);if("playable-ad"===this.h||"instant-games"===this.h)this.s=!1;if("cordova"===this.h&&this.s&&z){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);b&&
90<=parseInt(b[1],10)||(this.s=!1)}this.N()?self.chrome.webview.addEventListener("message",b=>this.hb(b.data)):"macos-wkwebview"===this.h&&(self.C3WrapperOnMessage=b=>this.hb(b));this.ra=this.F=null;"html5"!==this.h||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.g("canvas","update-size",b=>this.Yb(b));this.g("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.g("canvas","cleanup-html-layers",()=>this.Pb());this.g("runtime","cordova-fetch-local-file",b=>this.Qb(b));this.g("runtime","create-job-worker",()=>this.Rb());this.g("runtime","send-wrapper-extension-message",b=>this.Xb(b));"cordova"===this.h?document.addEventListener("deviceready",()=>this.oa(a)):this.oa(a)}wb(){return this.l[0].canvas}ya(a){return Math.min(a,this.l.length-1)}ma(a){if(0>a||a>=this.l.length)throw new RangeError("invalid canvas layer");return this.l[a].la}Ab(){return ca&&
"cordova"===this.h}$(){const a=navigator.userAgent;return ca&&la.has(this.h)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}yb(){return z}Za(){return z&&la.has(this.h)}$a(){return"windows-webview2"===this.h||!!("preview"===this.h&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}N(){return this.$a()||"xbox-uwp-webview2"===this.h}async oa(a){this.s&&!await ea()&&(this.s=!1);"macos-wkwebview"===this.h?this.aa({type:"ready"}):this.N()&&(this.ac(),this.tb=(await this.Ob()).registeredComponentIds);
if("playable-ad"===this.h){this.F=self.c3_base64files;this.ra={};await this.Gb();for(let d=0,e=a.W.length;d<e;++d){var b=a.W[d];this.ra.hasOwnProperty(b)?a.W[d]={kc:!0,oc:this.ra[b]}:this.F.hasOwnProperty(b)&&(a.W[d]=URL.createObjectURL(this.F[b]))}a.va=[]}if("nwjs"===this.h&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.ab(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.mc?this.o=a.mc:(b=location.origin,this.o=("null"===b?"file:///":b)+location.pathname,b=this.o.lastIndexOf("/"),
-1!==b&&(this.o=this.o.substr(0,b+1)));a.sc&&(this.ka=a.sc);b=new MessageChannel;this.ha=b.port1;this.ha.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Tb(d));this.fa=new self.Bb(this);await na(this.fa);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.s?await this.Nb(a,b.port2):await this.Mb(a,b.port2)}Ba(a){a=this.ka.hasOwnProperty(a)?this.ka[a]:a.endsWith("/workermain.js")&&this.ka.hasOwnProperty("workermain.js")?this.ka["workermain.js"]:"playable-ad"===this.h&&this.F.hasOwnProperty(a)?this.F[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async xa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.h&&this.Ja)return a=await this.wa(d.jc?a:this.T+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}C(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}fb(a){var b=this.o,d=location.href,e=this.C(),f=this.u(),g=window.devicePixelRatio,h=c.Z(),k=a.xc,l=window.cr_previewImageBlobs||this.F,n=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,r=window.cr_swClientId||
"";a=a.ub;var Ha=(new URLSearchParams(self.location.search)).has("debug"),W=this.fa;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:l,previewProjectFileBlobs:n,previewProjectFileSWUrls:q,swClientId:r,exportType:a,isDebug:Ha,ife:!!self.wc,jobScheduler:{inputPort:W.Ia,outputPort:W.Qa,maxNumWorkers:W.dc},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.T+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.T+"opus.wasm.wasm",isFileProtocol:this.Ja,isiOSCordova:this.Ab(),isiOSWebView:this.$(),isWindowsWebView2:this.$a(),isAnyWebView2Wrapper:this.N(),wrapperComponentIds:this.tb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Nb(a,b){const d=this.Ba(a.rc);"preview"===this.h?(this.V=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const q=r=>{this.V.removeEventListener("message",q);r.data&&"ok"===r.data.type?l():n()};this.V.addEventListener("message",
q);this.V.postMessage({type:"construct-worker-init","import":(new URL(d,this.o)).toString()})})):this.V=await this.xa(d,this.o,{type:"module",name:"Runtime",jc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.l.push({canvas:e,la:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
let h=a.va||[],k=a.W;h=await Promise.all(h.map(l=>this.O(l)));k=await Promise.all(k.map(l=>this.O(l)));if("cordova"===this.h)for(let l=0,n=a.ua.length;l<n;++l){const q=a.ua[l],r=q[0];if(r===a.Wa||"scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))q[1]=await this.O(r)}this.V.postMessage(Object.assign(this.fb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.ua,mainProjectScript:a.Wa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[b,f,...oa(this.fa)]);this.R=F.map(l=>new l(this));this.eb();I(e);J(g);pa(this.L);self.c3_callFunction=(l,n)=>{var q=this.L;return q.i.Cb(q.ca,{name:l,params:n})};"preview"===this.h&&(self.goToLastErrorScript=()=>this.na("runtime","go-to-last-error-script"))}async Mb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.l.push({canvas:d,la:e});window.c3canvas=
d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.R=F.map(h=>new h(this));this.eb();I(d);J(e);e=a.W.map(h=>"string"===typeof h?(new URL(h,this.o)).toString():h);if(Array.isArray(a.va)){var f=[...a.va].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.O(h)));await Promise.all(e.map(h=>B(h)));e=self.C3_ProjectScriptsStatus;f=a.Wa;const g=a.ua;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.O(k),await B(k),"preview"!==this.h||
e[h]||this.ib(h,"main script did not run to completion")}catch(l){this.ib(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.O(k),await B(k);"preview"===this.h&&"object"!==typeof self.tc.vc?(this.qa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.fb(a),{isInWorker:!1,
messagePort:b,canvas:d,runOnStartupFunctions:ka}),pa(this.L),this.gb(),this.Na=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Na,a))}ib(a,b){this.qa();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}gb(){this.qa()}qa(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=
null)}async Rb(){const a=await qa(this.fa);return{outputPort:a,transferables:[a]}}Yb(a){if(!this.pb){var b=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,la:h}of this.l)g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.qb&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.qb=
!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(b<this.l.length)for(;this.l.length>b;){const {canvas:l,la:n}=this.l.pop();n.remove();this.s&&!d?this.Ra.push(l):l.remove()}else if(b>this.l.length)for(let l=0,n=b-this.l.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.s?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),
d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),b.style.width=e,b.style.height=f,b.style.marginLeft=g,b.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,I(b),J(d),this.l.push({canvas:b,la:d});for(const l of this.R)if(l instanceof window.M&&l.P)for(const n of l.K.values())e=l.i.ya(n.Ua),f=n.D,-1!==e&&-1!==f&&e!==f&&(f=n.da,f.remove(),l.i.ma(e).appendChild(f),n.D=e);this.Ea();return{addedCanvases:a,transferables:k}}Pb(){for(const a of this.Ra)a.remove();
this.Ra.length=0}Ea(){this.Sa||(this.Sa=!0,this.ab(this.sb))}Jb(){this.$b(this.sb);this.Sa=!1;let a=[];for(var b of this.R)if(b instanceof window.M){var d=b.P?[...b.K.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.D,l=h.D;return k!==l?k-l:g.ea-h.ea});let e=d=b=0,f=a.length;for(;e<f;++e){const g=a[e];g.D!==b&&(this.cb(b,a.slice(d,e)),b=g.D,d=e)}d<e&&this.cb(b,a.slice(d,e))}cb(a,b){if(!(1>=b.length||a>=this.l.length)){b=b.map(k=>k.da);var d=new Set(b);a=this.ma(a);for(var e=Array.from(a.children).filter(k=>
d.has(k)),f=0,g=Math.min(b.length,e.length);f<g&&b[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(b[h])}}Lb(){if(this.s)throw Error("not available in worker mode");return this.Na}na(a,b,d,e){this.ha.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Cb(a,b){const d=ja++,e=new Promise((f,g)=>{H.set(d,{resolve:f,reject:g})});this.ha.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,
responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;if("event"===b)return this.Sb(a);if("result"===b)this.Vb(a);else if("runtime-ready"===b)this.Wb();else if("alert-error"===b)this.qa(),alert(a.message);else if("creating-runtime"===b)this.gb();else throw Error(`unknown message '${b}'`);}Sb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(b))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${b}' handler '${d}':`,h);null!==f&&this.pa(f,
!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.pa(f,!0,h)).catch(h=>{console.error(`Rejection from '${b}' handler '${d}':`,h);this.pa(f,!1,""+h)}):this.pa(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}pa(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.ha.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Vb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=H.get(b);d?e.resolve(a):
e.reject(a);H.delete(b)}g(a,b,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static G(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}eb(){for(const a of this.R)if("runtime"===a.ca){this.L=a;return}throw Error("cannot find runtime DOM handler");}Tb(a){this.na("debugger","message",a)}Wb(){for(const a of this.R)a.Xa()}static Z(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||ma)}static jb(a){ma=!!a}ab(a){this.ia.add(a);this.Da()}$b(a){this.ia.delete(a);0===this.ia.size&&this.bb()}Da(){-1===this.S&&0<this.ia.size&&(this.S=requestAnimationFrame(this.fc))}bb(){-1!==this.S&&(cancelAnimationFrame(this.S),this.S=-1)}Ub(){this.S=-1;for(const a of this.ia)a();this.Da()}Ca(){this.L.Ca()}Db(){this.pb=!0}xb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}zb(a){return!this.xb(a)}async O(a){return"cordova"===
this.h&&(a.startsWith("file:")||this.Ja&&this.zb(a))?(a.startsWith(this.o)&&(a=a.substr(this.o.length)),a=await this.wa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Qb(a){const b=a.filename;switch(a.as){case "text":return await this.vb(b);case "buffer":return await this.wa(b);default:throw Error("unsupported type");}}Ya(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async vb(a){a=
await this.Ya(a);return await ha(a)}za(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.Hb(a.filename,a.pc,a.ic)}}wa(a){return new Promise((b,d)=>{D.push({filename:a,pc:e=>{E--;this.za();b(e)},ic:e=>{E--;this.za();d(e)}});this.za()})}async Hb(a,b,d){try{const e=await this.Ya(a),f=await ia(e);b(f)}catch(e){d(e)}}hb(a){if("entered-fullscreen"===a)c.jb(!0),K(this.L);else if("exited-fullscreen"===a)c.jb(!1),K(this.L);else if("object"===typeof a){const b=a.type;"wrapper-init-response"===b?(this.Va(a),
this.Va=null):"extension-message"===b?this.na("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Xb(a){this.aa({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}aa(a){this.N()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.h&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}ac(){window.moveTo=(a,b)=>
{this.aa({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.aa({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Ob(){return this.N()?new Promise(a=>{this.Va=a;this.aa({type:"wrapper-init"})}):Promise.resolve()}async Gb(){const a=[];for(const [b,d]of Object.entries(this.F))a.push(this.Fb(b,d));await Promise.all(a)}async Fb(a,b){if("object"===typeof b)this.F[a]=new Blob([b.str],{type:b.type}),this.ra[a]=b.str;else{let d=
await this.Kb(b);d||(d=this.Ib(b));this.F[a]=d}}async Kb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",b),null}}Ib(a){a=this.Zb(a);return this.Eb(a.data,a.lc)}Zb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");
a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{lc:a,data:d}}Eb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";
const L=self.A,ra=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),N={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},sa={dispatchUserScriptEvent:!0},ta={dispatchRuntimeEvent:!0};function ua(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}function va(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}
async function O(c){c=URL.createObjectURL(c);try{return await va(c)}finally{URL.revokeObjectURL(c)}}function wa(c){return new Promise((a,b)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsText(c)})}
async function xa(c,a,b){if(!/firefox/i.test(navigator.userAgent))return await O(c);var d=await wa(c);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await O(c)}e.setAttribute("width",a+"px");e.setAttribute("height",b+"px");d=(new XMLSerializer).serializeToString(d);c=new Blob([d],{type:"image/svg+xml"});return await O(c)}
function ya(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const za=new Set(["input","textarea","datalist","select"]),Aa=new Set(["canvas","body","html"]);function P(c){c.target.tagName&&Aa.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function Ba(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Ca(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await O(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await xa(c,a,b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let Da=!1;document.addEventListener("pause",()=>Da=!0);document.addEventListener("resume",()=>Da=!1);function I(c){c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);c.addEventListener("pointerdown",P)}function J(c){c.addEventListener("selectstart",Ba);c.addEventListener("gesturehold",Ba);c.addEventListener("touchstart",Ba)}function pa(c){c.nb=!0;c.Ma=c.i.C();c.ga=c.i.u()}
function K(c){if(!c.v){var a=L.Z();a&&"any"!==c.Ta&&Ea(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.C(),innerHeight:c.u()})}}async function Fa(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ga(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ia(c){return await self.C3_GetSvgImageSize(c.blob)}function Ja(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ka(c){self.setTimeout(()=>{c.mb=!0},1E3);"cordova"===c.i.h?(document.addEventListener("pause",()=>La(c,!0)),document.addEventListener("resume",()=>La(c,!1))):document.addEventListener("visibilitychange",()=>La(c,"hidden"===document.visibilityState));c.sa=!("hidden"!==document.visibilityState&&!Da);return{isSuspended:c.sa}}
function Ma(c){c.lb||(c.lb=!0,window.addEventListener("deviceorientation",a=>{c.v||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},N)}),window.addEventListener("deviceorientationabsolute",a=>{c.v||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},N)}))}
function Na(c){c.kb||(c.kb=!0,window.addEventListener("devicemotion",a=>{if(!c.v){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},N)}}))}async function Oa(c){await ua(c.url)}
function Pa(c,a){c.ob=a.message;-1===c.Ga&&(c.Ga=setTimeout(()=>{c.Ga=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.ob)},250))}function Qa(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:L.Z(),innerWidth:c.C(),innerHeight:c.u()})}
function La(c,a){c.sa!==a&&((c.sa=a)?c.i.bb():c.i.Da(),m(c,"visibilitychange",{hidden:a}),!a&&c.i.$()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Ra(c,a,b){"Backspace"===b.key&&P(b);if(c.i.N()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(b.key)||b.ctrlKey&&d.includes(b.key))&&b.preventDefault()}c.v||(d=ra.get(b.code)||b.code,p(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},N))}
function Q(c,a,b,d){c.v||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||p(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.I,pageX:b.pageX,pageY:b.pageY+c.I,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function R(c,a,b){if(!c.v){var d=0;"mouse"===b.pointerType&&(d=c.Pa);p(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.I,pageX:b.pageX,pageY:b.pageY+c.I,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},N);"mouse"===b.pointerType&&(c.Pa=
b.buttons)}}function Sa(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.I=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.I=a))}}
function Ta(c,a,b,d){const e=c.C(),f=c.u();c.U=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:L.Z()}):10>d&&Ua(c,e,f,d+1)}function Ua(c,a,b,d){-1!==c.U&&clearTimeout(c.U);c.U=setTimeout(()=>Ta(c,a,b,d),48)}
function Ea(c){c=c.Ta;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Va(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
L.G(class extends self.Y{constructor(c){super(c,"runtime");this.nb=!1;this.U=-1;this.Ta="any";this.sa=this.kb=this.lb=!1;this.ta=document.createElement("div");this.ta.className="c3-screen-reader-text";this.ta.setAttribute("aria-live","polite");document.body.appendChild(this.ta);this.J=null;this.v=!1;this.ob="";this.Ga=-1;this.mb=!1;this.Ma=c.C();this.ga=c.u();this.I=this.ja=0;c.g("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.g("runtime","load-webfonts",b=>Fa(b));c.g("runtime","raster-svg-image",b=>Ga(b));c.g("runtime","get-svg-image-size",b=>Ia(b));c.g("runtime","set-target-orientation",b=>{this.Ta=b.targetOrientation});c.g("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.g("runtime","post-to-debugger",b=>Ja(b));c.g("runtime","go-to-script",b=>Ja(b));c.g("runtime","before-start-ticking",()=>Ka(this));c.g("runtime","debug-highlight",
b=>{if(b.show){this.J||(this.J=document.createElement("div"),this.J.id="inspectOutline",document.body.appendChild(this.J));var d=this.J;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.J&&(this.J.style.display="none")});c.g("runtime","enable-device-orientation",()=>Ma(this));c.g("runtime","enable-device-motion",()=>Na(this));c.g("runtime","add-stylesheet",b=>Oa(b));c.g("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.g("runtime","alert",b=>{alert(b.message)});c.g("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.ta.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+
b.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.g("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.g("runtime","set-exporting-to-video",b=>{this.v=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.i.wb().style.display="";this.i.Db()});c.g("runtime","export-to-video-progress",b=>Pa(this,b));c.g("runtime","exported-to-video",b=>{window.hc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.g("runtime","exported-to-image-sequence",b=>{window.hc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||
ya(d)||b.preventDefault()});window.addEventListener("selectstart",P);window.addEventListener("gesturehold",P);window.addEventListener("touchstart",P,{passive:!1});window.addEventListener("pointerdown",P,{passive:!1});this.Pa=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.v&&this.nb){var b=this.C();var d=this.u();if(this.i.Za()){if(this.mb){if(this.Ma===
b&&d<this.ga){this.ja=this.ga-d;Sa(this,this.ga,this.ja);b=void 0;break a}0<this.ja&&(this.ja=0,Sa(this,d,this.ja))}this.Ma=b;this.ga=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:L.Z()});this.i.$()&&(-1!==this.U&&clearTimeout(this.U),Ta(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>K(this));window.addEventListener("webkitfullscreenchange",()=>K(this));window.addEventListener("mozfullscreenchange",()=>K(this));
window.addEventListener("fullscreenerror",b=>Qa(this,b));window.addEventListener("webkitfullscreenerror",b=>Qa(this,b));window.addEventListener("mozfullscreenerror",b=>Qa(this,b));if(c.$()){if(window.visualViewport){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var b=e.tagName.toLowerCase();
var d=new Set("email number password search tel text url".split(" "));b="textarea"===b?!0:"input"===b?d.has(e.type.toLowerCase()||"text"):ya(e)}else b=!1}b||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Oa=new Set;this.ec=new WeakSet;this.cc=!1}Xa(){window.addEventListener("focus",()=>{m(this,"window-focus",null,ta)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",
{parentHasFocus:a},ta);this.Pa=0});window.addEventListener("focusin",a=>{a=a.target;(za.has(a.tagName.toLowerCase())||ya(a))&&m(this,"keyboard-blur",null,ta)});window.addEventListener("keydown",a=>Ra(this,"keydown",a));window.addEventListener("keyup",a=>Ra(this,"keyup",a));window.addEventListener("mousedown",a=>Q(this,"mousedown",a,sa));window.addEventListener("mousemove",a=>Q(this,"mousemove",a,sa));window.addEventListener("mouseup",a=>Q(this,"mouseup",a,sa));window.addEventListener("dblclick",a=>
Q(this,"dblclick",a,N));window.addEventListener("wheel",a=>{this.v||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.I,pageX:a.pageX,pageY:a.pageY+this.I,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},N)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Va(a.target)&&document.activeElement&&!Va(document.activeElement)&&document.activeElement.blur();R(this,"pointerdown",a)});this.i.s&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{R(this,"pointermove",a)}):window.addEventListener("pointermove",a=>R(this,"pointermove",a));window.addEventListener("pointerup",a=>R(this,"pointerup",a));window.addEventListener("pointercancel",a=>R(this,"pointercancel",a));const c=()=>this.Ca();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",
c,!0);this.i.yb()&&!this.i.Za()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Sa(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}));this.i.$()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}C(){return this.i.C()}u(){return this.i.u()}Ca(){var c=[...this.Oa];this.Oa.clear();if(!this.cc)for(const a of c)(c=a.play())&&c.catch(()=>{this.ec.has(a)||this.Oa.add(a)})}});
"use strict";async function na(c){if(c.bc)throw Error("already initialised");c.bc=!0;var a=c.H.Ba(("playable-ad"===c.H.h?c.H.T:"")+"dispatchworker.js");c.Fa=await c.H.xa(a,c.ba,{name:"DispatchWorker"});a=new MessageChannel;c.Ia=a.port1;c.Fa.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Qa=await qa(c)}function oa(c){return[c.Ia,c.Qa]}
async function qa(c){const a=c.rb.length;var b=c.H.Ba(("playable-ad"===c.H.h?c.H.T:"")+"jobworker.js");b=await c.H.xa(b,c.ba,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Fa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.rb.push(b);return e.port1}
self.Bb=class{constructor(c){this.H=c;this.ba=c.o;this.ba="preview"===c.h?this.ba+"workers/":this.ba+c.T;this.dc=Math.min(navigator.hardwareConcurrency||2,16);this.Fa=null;this.rb=[];this.Qa=this.Ia=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.A({qc:!0,rc:"workermain.js",W:["scripts/c3runtime.js"],ua:[],Wa:"",nc:"scripts/",va:[],ub:"html5"}));"use strict";function S(c){c.stopPropagation()}
self.A.G(class extends self.M{constructor(c){super(c,"button")}X(c,a){const b=document.createElement("input");var d=b;a.isCheckbox?(b.type="checkbox",d=document.createElement("label"),d.appendChild(b),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):b.type="button";d.style.position="absolute";d.addEventListener("pointerdown",S);d.addEventListener("pointermove",
S);d.addEventListener("pointerrawupdate",S);d.addEventListener("pointerup",S);d.addEventListener("mousedown",S);d.addEventListener("mouseup",S);d.addEventListener("keydown",S);d.addEventListener("keyup",S);d.addEventListener("contextmenu",e=>e.preventDefault());b.addEventListener("click",()=>y(this,"click",c,{isChecked:b.checked}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.B(d,a);return d}Aa(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}B(c,a){const b="input"===c.tagName.toLowerCase()?
c:c.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;c.title=a.title;c===b?b.value=a.text:c.lastChild.textContent=a.text}});"use strict";async function Wa(c,a){a=a.type;let b=!0;0===a?b=await Xa():1===a&&(b=await Ya());m(c,"permission-result",{type:a,result:b})}
async function Xa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Ya(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.A.G(class extends self.Y{constructor(c){super(c,"touch");t(this,"request-permission",a=>Wa(this,a))}});"use strict";function T(c){c.stopPropagation()}function Za(c){const a=document.createElement("option");a.text=c;return a}
function $a(c){const a=c.selectedIndex,b=[];for(let d=0,e=c.length;d<e;++d)c.options[d].selected&&b.push(d);return{selectedIndex:a,selectedIndices:b}}
self.A.G(class extends self.M{constructor(c){super(c,"list");w(this,"set-selected-index",(a,b)=>{a.selectedIndex=b.selectedIndex});w(this,"add-item",(a,b)=>{const d=b.index;b=Za(b.text);0>d?a.add(b):a.add(b,d)});w(this,"remove-item",(a,b)=>{a.remove(b.index)});w(this,"set-item",(a,b)=>{a.options[b.index].text=b.text});w(this,"clear",a=>{a.innerHTML=""});w(this,"load-state",(a,b)=>{a.innerHTML="";for(const d of b.items)a.add(Za(d));a.selectedIndex=b.selectedIndex;for(const d of b.selectedIndices)if(b=
a.options[d])b.selected=!0})}X(c,a){const b=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;b||(f.size=2);for(const g of e)f.add(Za(g));f.addEventListener("pointerdown",T);f.addEventListener("pointermove",T);f.addEventListener("pointerrawupdate",T);f.addEventListener("pointerup",T);f.addEventListener("mousedown",T);f.addEventListener("mouseup",T);f.addEventListener("click",
g=>{g.stopPropagation();y(this,"click",c,$a(f))});f.addEventListener("dblclick",g=>{g.stopPropagation();y(this,"dblclick",c,$a(f))});f.addEventListener("change",()=>v(this,"change",c,$a(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.B(f,a);return f}B(c,a){c.title=a.title;c.disabled=!a.isEnabled;c.multiple=!!a.isMultiSelect}});"use strict";function U(c){c.stopPropagation()}function ab(c){13!==c.which&&27!==c.which&&c.stopPropagation()}
self.A.G(class extends self.M{constructor(c){super(c,"text-input");w(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}X(c,a){let b;const d=a.type;"textarea"===d?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=d);b.style.position="absolute";b.autocomplete="off";b.addEventListener("pointerdown",U);b.addEventListener("pointermove",U);b.addEventListener("pointerrawupdate",U);b.addEventListener("pointerup",U);b.addEventListener("mousedown",
U);b.addEventListener("mouseup",U);b.addEventListener("keydown",ab);b.addEventListener("keyup",ab);b.addEventListener("click",e=>{e.stopPropagation();y(this,"click",c)});b.addEventListener("dblclick",e=>{e.stopPropagation();y(this,"dblclick",c)});b.addEventListener("input",()=>v(this,"change",c,{text:b.value}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.B(b,a);return b}B(c,a){c.value=a.text;c.placeholder=a.placeholder;c.title=a.title;c.disabled=!a.isEnabled;c.readOnly=a.isReadOnly;
c.spellcheck=a.spellCheck;a=a.maxLength;0>a?c.removeAttribute("maxlength"):c.setAttribute("maxlength",a)}});"use strict";function V(c){c.stopPropagation()}
self.A.G(class extends self.M{constructor(c){super(c,"progress-bar")}X(c,a){const b=document.createElement("progress");b.style.position="absolute";b.style.userSelect="none";b.style.webkitUserSelect="none";b.addEventListener("pointerdown",V);b.addEventListener("pointermove",V);b.addEventListener("pointerrawupdate",V);b.addEventListener("pointerup",V);b.addEventListener("mousedown",V);b.addEventListener("mouseup",V);b.addEventListener("click",()=>y(this,"click",c));a.id&&(b.id=a.id);a.className&&(b.className=
a.className);this.B(b,a);return b}B(c,a){c.title=a.title;const b=a.value;a=a.max;0<a&&0<=b?(c.max=a,c.value=b):(c.removeAttribute("value"),c.removeAttribute("max"))}});"use strict";async function bb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(c){return console.error("[Construct] Error requesting persistent storage: ",c),{isOk:!1}}}
self.A.G(class extends self.Y{constructor(c){super(c,"localstorage");u(this,[["init",()=>this.oa()],["request-persistent",()=>bb()]])}async oa(){let c=!1;try{c=await navigator.storage.persisted()}catch(a){c=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:c}}});"use strict";function cb(c,a){return new Promise((b,d)=>{const e=(f,g)=>{c.m=g;m(c,"login",{state:g,error:f})};window.cordova?db(c,b,d,e):eb(c,a,b,d,e)})}
async function fb(c){if(!c.m)return null;const a={id:"",display:"",avatar:"",givenName:"",familyName:""};c=window.cordova?await X(c,"getPlayerData"):await Z("players/me");a.id=c.playerId||"";a.display=c.displayName||"";a.avatar=c.avatarImageUrl||"";c.name&&(a.givenName=c.name.givenName||"",a.familyName=c.name.familyName||"");return a}
async function gb(c,a){if(!c.m)return null;const b={page:[],total:0,best:0,formattedbest:"",besttag:"",rank:0,formattedrank:""};c=c.j?await X(c,"getHiScores",a):await Z(`leaderboards/${a.leaderboardId}/${a.type}/${a.collection}`,a);b.total=parseInt(c.numScores,10)||0;c.playerScore&&(b.best=parseInt(c.playerScore.scoreValue,10)||0,b.formattedbest=c.playerScore.formattedScore||"",b.besttag=c.playerScore.scoreTag||"",b.rank=parseInt(c.playerScore.scoreRank,10)||0,b.formattedrank=c.playerScore.formattedScoreRank||
"");b.page=c.items;return b}async function hb(c,a){const b=a.which;if(!c.m)return null;if(c.j){c=await X(c,"getAchievements",a);a=new Map;const d=c.items;for(const e of c.items)a.set(e.id,{name:e.name,description:e.description,type:e.achievementType,totalSteps:e.totalSteps,revealedUrl:e.revealedIconUrl,unlockedUrl:e.unlockedIconUrl});return{page:d.filter(e=>e.state===b),id:a}}return{page:(await Z("players/me/achievements",a)).items.filter(d=>d.state===b),id:null}}
async function ib(c,a){a=a.reload;if(!c.m)return null;if(c.j)return hb(c,{which:"ALL",reload:a});c=await Z("achievements");a=new Map;for(const b of c.items)a.set(b.id,{name:b.name,description:b.description,type:b.achievementType,totalSteps:b.totalSteps,revealedUrl:b.revealedIconUrl,unlockedUrl:b.unlockedIconUrl});return{page:null,id:a}}async function jb(c,a){a=a.id;if(!c.m)return null;c.j?await X(c,"revealAchievement",{achievementId:a}):await Z(`achievements/${a}/reveal`,null,"post");return!0}
async function kb(c,a){a=a.id;if(!c.m)return null;c.j?await X(c,"unlockAchievement",{achievementId:a}):await Z(`achievements/${a}/unlock`,null,"post");return!0}async function lb(c,a){const b=a.id;a=a.steps;if(!c.m)return null;c.j?await X(c,"incrementAchievement",{achievementId:b,numSteps:a}):await Z(`achievements/${b}/increment`,{stepsToIncrement:a},"post");return!0}
async function mb(c,a){const b=a.id;a=a.steps;if(!c.m)return null;c.j?await X(c,"setStepsAchievement",{achievementId:b,numSteps:a}):await Z(`achievements/${b}/setStepsAtLeast`,{steps:a},"post");return!0}function X(c,a,b={}){return new Promise((d,e)=>{c.j[a](b,(f,g)=>{f?e(f):d(g)})})}
function Z(c,a,b="get"){return new Promise((d,e)=>{self.gapi.client.request({path:"/games/v1/"+c,method:b,params:a,callback:function(f){let g=f?f.error:"no_response";g?("object"===typeof g?g="string"===typeof g.message?g.message:"unknown":"string"!==typeof g&&(g="unknown"),e(g)):d(f)}})})}function db(c,a,b,d){const e=window.cordova.plugins.ConstructPlayGames;e?(c.j=e,a(),c.Ka=!0,e.setCallback(d),e.silentSignIn()):b()}
function eb(c,a,b,d,e){const f=(g,h)=>{const k=document.createElement("meta");k.setAttribute("name","google-signin-"+g);k.setAttribute("content",h);document.head.appendChild(k)};window.googlePlayLoadCallback=(...g)=>{c.Ka=!0;b(...g)};window.googlePlaySigninCallback=g=>{g.status&&g.status.signed_in?e("",!0):e(g.error+"",!1)};f("clientid",a);f("cookiepolicy","single_host_origin");f("callback","googlePlaySigninCallback");f("scope","https://www.googleapis.com/auth/games");a=document.createElement("script");
a.setAttribute("type","text/javascript");a.setAttribute("async","");a.setAttribute("src","https://apis.google.com/js/client.js?onload=googlePlayLoadCallback");a.addEventListener("error",()=>d("failed to load script"));document.head.appendChild(a)}
self.A.G(class extends self.Y{constructor(c){super(c,"googleplay");u(this,[["load",([a])=>cb(this,a)],["signin",()=>{if(!this.Ka||this.m)var a=null;else this.j?this.j.signin():self.gapi.auth.signIn({callback:window.googlePlaySigninCallback}),a=void 0;return a}],["signout",()=>{if(this.m){this.j?this.j.signout():self.gapi.auth.signOut();var a=void 0}else a=null;return a}],["getplayer",()=>fb(this)],["submitscore",a=>this.m?this.j?X(this,"submitScore",a):Z(`leaderboards/${a.leaderboardId}/scores`,a,
"post"):null],["requestscores",a=>gb(this,a)],["requestachievements",a=>hb(this,a)],["requestmetadata",a=>ib(this,a)],["reveal",a=>jb(this,a)],["unlock",a=>kb(this,a)],["increment",a=>lb(this,a)],["setsteps",a=>mb(this,a)],["showleaderboard",a=>{a=a.id;if(this.m)if(this.j)a=null!=a?X(this,"showLeaderboard",{leaderboardId:a}):X(this,"showLeaderboards");else throw Error("not available");else a=null;return a}],["showachievements",()=>{if(this.m)if(this.j)var a=X(this,"showAchievements");else throw Error("not available");
else a=null;return a}]]);this.Ka=this.m=!1}});
