window.DOMHandler=class{constructor(b,a){this._iRuntime=b;this._componentId=a;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(b,a,c,d){this._iRuntime.PostToRuntimeComponent(this._componentId,b,a,c,d)}PostToRuntimeAsync(b,a,c,d){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,b,a,c,d)}_PostToRuntimeMaybeSync(b,a,c){this._iRuntime.UsesWorker()?this.PostToRuntime(b,a,c):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",component:this._componentId,
handler:b,dispatchOpts:c||null,data:a,responseId:null})}AddRuntimeMessageHandler(b,a){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,b,a)}AddRuntimeMessageHandlers(b){for(const [a,c]of b)this.AddRuntimeMessageHandler(a,c)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&(this._iRuntime._RemoveRAFCallback(this._tickCallback),
this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(b,a){this._callback=b;this._interval=a;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(b){this._canRunImmediate=!!b}Call(){if(-1===this._timerId){var b=Date.now(),a=b-this._lastCallTime,c=this._interval;a>=c&&this._canRunImmediate?(this._lastCallTime=b,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(c-a,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
class ElementState{constructor(b){this._elem=b;this._hadFirstUpdate=!1;this._isVisibleFlag=!0;this._htmlZIndex=this._actualHtmlIndex=this._wantHtmlIndex=-1}SetVisibleFlag(b){this._isVisibleFlag=!!b}GetVisibleFlag(){return this._isVisibleFlag}HadFirstUpdate(){return this._hadFirstUpdate}SetHadFirstUpdate(){this._hadFirstUpdate=!0}GetWantHTMLIndex(){return this._wantHtmlIndex}SetWantHTMLIndex(b){this._wantHtmlIndex=b}GetActualHTMLIndex(){return this._actualHtmlIndex}SetActualHTMLIndex(b){this._actualHtmlIndex=
b}SetHTMLZIndex(b){this._htmlZIndex=b}GetHTMLZIndex(){return this._htmlZIndex}GetElement(){return this._elem}}
window.DOMElementHandler=class extends self.DOMHandler{constructor(b,a){super(b,a);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",c=>this._OnCreate(c)],["destroy",c=>this._OnDestroy(c)],["set-visible",c=>this._OnSetVisible(c)],["update-position",c=>this._OnUpdatePosition(c)],["update-state",c=>this._OnUpdateState(c)],["focus",c=>this._OnSetFocus(c)],["set-css-style",c=>this._OnSetCssStyle(c)],["set-attribute",c=>this._OnSetAttribute(c)],["remove-attribute",
c=>this._OnRemoveAttribute(c)]]);this.AddDOMElementMessageHandler("get-element",c=>c)}SetAutoAttach(b){this._autoAttach=!!b}AddDOMElementMessageHandler(b,a){this.AddRuntimeMessageHandler(b,c=>{const d=this.GetElementById(c.elementId);return a(d,c)})}_OnCreate(b){const a=b.elementId,c=this.CreateElement(a,b),d=new ElementState(c);this._elementMap.set(a,d);c.style.boxSizing="border-box";c.style.display="none";d.SetVisibleFlag(b.isVisible);var e=this._GetFocusElement(c);e.addEventListener("focus",f=>
this._OnFocus(a));e.addEventListener("blur",f=>this._OnBlur(a));e=b.htmlIndex;d.SetWantHTMLIndex(e);d.SetHTMLZIndex(b.htmlZIndex);this._autoAttach&&(b=this.GetRuntimeInterface().GetAvailableHTMLIndex(e),d.SetActualHTMLIndex(b),this.GetRuntimeInterface().GetHTMLWrapElement(b).appendChild(c))}CreateElement(b,a){throw Error("required override");}DestroyElement(b){}_OnDestroy(b){b=b.elementId;const a=this.GetElementById(b);this.DestroyElement(a);this._autoAttach&&a.parentElement.removeChild(a);this._elementMap.delete(b)}PostToRuntimeElement(b,
a,c){c||(c={});c.elementId=a;this.PostToRuntime(b,c)}_PostToRuntimeElementMaybeSync(b,a,c){c||(c={});c.elementId=a;this._PostToRuntimeMaybeSync(b,c)}_OnSetVisible(b){if(this._autoAttach){var a=this._elementMap.get(b.elementId),c=a.GetElement();a.HadFirstUpdate()?c.style.display=b.isVisible?"":"none":a.SetVisibleFlag(b.isVisible)}}_OnUpdatePosition(b){if(this._autoAttach){var a=this._elementMap.get(b.elementId),c=a.GetElement(),d=this.GetRuntimeInterface();c.style.left=b.left+"px";c.style.top=b.top+
"px";c.style.width=b.width+"px";c.style.height=b.height+"px";var e=b.fontSize;null!==e&&(c.style.fontSize=e+"em");e=b.htmlIndex;a.SetWantHTMLIndex(e);e=d.GetAvailableHTMLIndex(e);e!==a.GetActualHTMLIndex()&&(c.remove(),d.GetHTMLWrapElement(e).appendChild(c),a.SetActualHTMLIndex(e),d._UpdateHTMLElementsZOrder());b=b.htmlZIndex;b!==a.GetHTMLZIndex()&&(a.SetHTMLZIndex(b),d._UpdateHTMLElementsZOrder());a.HadFirstUpdate()||(a.SetHadFirstUpdate(),a.GetVisibleFlag()&&(c.style.display=""))}}_OnHTMLLayersChanged(){if(this._autoAttach)for(const a of this._elementMap.values()){const c=
this.GetRuntimeInterface().GetAvailableHTMLIndex(a.GetWantHTMLIndex());var b=a.GetActualHTMLIndex();-1!==c&&-1!==b&&c!==b&&(b=a.GetElement(),b.remove(),this.GetRuntimeInterface().GetHTMLWrapElement(c).appendChild(b),a.SetActualHTMLIndex(c))}}_GetAllElementStatesForZOrderUpdate(){return this._autoAttach?[...this._elementMap.values()]:null}_OnUpdateState(b){const a=this.GetElementById(b.elementId);this.UpdateState(a,b)}UpdateState(b,a){throw Error("required override");}_GetFocusElement(b){return b}_OnFocus(b){this.PostToRuntimeElement("elem-focused",
b)}_OnBlur(b){this.PostToRuntimeElement("elem-blurred",b)}_OnSetFocus(b){const a=this._GetFocusElement(this.GetElementById(b.elementId));b.focus?a.focus():a.blur()}_OnSetCssStyle(b){const a=this.GetElementById(b.elementId),c=b.prop;b=b.val;c.startsWith("--")?a.style.setProperty(c,b):a.style[c]=b}_OnSetAttribute(b){this.GetElementById(b.elementId).setAttribute(b.name,b.val)}_OnRemoveAttribute(b){this.GetElementById(b.elementId).removeAttribute(b.name)}GetElementById(b){const a=this._elementMap.get(b);
if(!a)throw Error(`no element with id ${b}`);return a.GetElement()}};"use strict";const isiOSLike=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),isAndroid=/android/i.test(navigator.userAgent);/safari/i.test(navigator.userAgent)&&/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let resolveCounter=0;
function AddScript(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.isStringSrc?new Promise(c=>{const d="c3_resolve_"+resolveCounter;++resolveCounter;self[d]=c;a.textContent=b.str+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function CheckSupportsWorkerMode(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"}),
c=new Worker(URL.createObjectURL(a),{get type(){b=!0}}),d=await new Promise(e=>{c.addEventListener("message",f=>{c.terminate();e(f.data)});c.postMessage("")});return b&&d}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let tmpAudio=new Audio;
const supportedAudioFormats={"audio/webm; codecs=opus":!!tmpAudio.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!tmpAudio.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!tmpAudio.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!tmpAudio.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!tmpAudio.canPlayType("audio/mp4"),"audio/mpeg":!!tmpAudio.canPlayType("audio/mpeg")};tmpAudio=null;
async function BlobToString(b){b=await BlobToArrayBuffer(b);return(new TextDecoder("utf-8")).decode(b)}function BlobToArrayBuffer(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const queuedArrayBufferReads=[];let activeArrayBufferReads=0;window.RealFile=window.File;const domHandlerClasses=[],runtimeEventHandlers=new Map,pendingResponsePromises=new Map;let nextResponseId=0;const runOnStartupFunctions=[];
self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");runOnStartupFunctions.push(b)};const WEBVIEW_EXPORT_TYPES=new Set(["cordova","playable-ad","instant-games"]);function IsWebViewExportType(b){return WEBVIEW_EXPORT_TYPES.has(b)}let isWrapperFullscreen=!1;
window.RuntimeInterface=class b{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._runtimeBaseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._runtimeDomHandler=null;this._isFirstSizeUpdate=!0;this._canvasLayers=[];this._pendingRemoveElements=[];this._pendingUpdateHTMLZOrder=!1;this._updateHTMLZOrderRAFCallback=()=>this._DoUpdateHTMLElementsZOrder();this._isExportingToVideo=!1;this._exportToVideoDuration=
0;this._jobScheduler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=new Set;this._wrapperInitResolve=null;this._wrapperComponentIds=[];this._exportType=a.exportType;this._isFileProtocol="file"===location.protocol.substr(0,4);if("playable-ad"===this._exportType||"instant-games"===this._exportType)this._useWorker=!1;if("cordova"===this._exportType&&this._useWorker&&isAndroid){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this._useWorker=
!1)}this.IsAnyWebView2Wrapper()?self.chrome.webview.addEventListener("message",c=>this._OnWrapperMessage(c.data)):"macos-wkwebview"===this._exportType&&(self.C3WrapperOnMessage=c=>this._OnWrapperMessage(c));this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.AddRuntimeComponentMessageHandler("canvas",
"update-size",c=>this._OnUpdateCanvasSize(c));this.AddRuntimeComponentMessageHandler("canvas","set-html-layer-count",c=>this._OnSetHTMLLayerCount(c));this.AddRuntimeComponentMessageHandler("canvas","cleanup-html-layers",()=>this._OnCleanUpHTMLLayers());this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",c=>this._OnCordovaFetchLocalFile(c));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",c=>this._OnCreateJobWorker(c));this.AddRuntimeComponentMessageHandler("runtime",
"send-wrapper-extension-message",c=>this._OnSendWrapperExtensionMessage(c));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);for(const {canvas:a,htmlWrap:c}of this._canvasLayers)a.remove(),
c.remove();this._canvasLayers.length=0}GetMainCanvas(){return this._canvasLayers[0].canvas}GetAvailableHTMLIndex(a){return Math.min(a,this._canvasLayers.length-1)}GetHTMLWrapElement(a){if(0>a||a>=this._canvasLayers.length)throw new RangeError("invalid canvas layer");return this._canvasLayers[a].htmlWrap}GetRuntimeBaseURL(){return this._runtimeBaseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsFileProtocol(){return this._isFileProtocol}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return isiOSLike&&
"cordova"===this._exportType}IsiOSWebView(){const a=navigator.userAgent;return isiOSLike&&IsWebViewExportType(this._exportType)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}IsAndroid(){return isAndroid}IsAndroidWebView(){return isAndroid&&IsWebViewExportType(this._exportType)}IsWindowsWebView2(){return"windows-webview2"===this._exportType||!!("preview"===this._exportType&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}IsAnyWebView2Wrapper(){return this.IsWindowsWebView2()||
"xbox-uwp-webview2"===this._exportType}async _Init(a){this._useWorker&&!await CheckSupportsWorkerMode()&&(this._useWorker=!1);"macos-wkwebview"===this._exportType?this._SendWrapperMessage({type:"ready"}):this.IsAnyWebView2Wrapper()&&(this._SetupWebView2Polyfills(),this._wrapperComponentIds=(await this._InitWrapper()).registeredComponentIds);if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let d=0,e=a.engineScripts.length;d<
e;++d){var c=a.engineScripts[d];this._localFileStrings.hasOwnProperty(c)?a.engineScripts[d]={isStringSrc:!0,str:this._localFileStrings[c]}:this._localFileBlobs.hasOwnProperty(c)&&(a.engineScripts[d]=URL.createObjectURL(this._localFileBlobs[c]))}a.workerDependencyScripts=[]}if("nwjs"===this._exportType&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this._AddRAFCallback(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.runtimeBaseUrl?this._runtimeBaseUrl=a.runtimeBaseUrl:(c=location.origin,
this._runtimeBaseUrl=("null"===c?"file:///":c)+location.pathname,c=this._runtimeBaseUrl.lastIndexOf("/"),-1!==c&&(this._runtimeBaseUrl=this._runtimeBaseUrl.substr(0,c+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);c=new MessageChannel;this._messageChannelPort=c.port1;this._messageChannelPort.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this._OnMessageFromDebugger(d));this._jobScheduler=new self.JobSchedulerDOM(this);
await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this._useWorker?await this._InitWorker(a,c.port2):await this._InitDOM(a,c.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?
this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a)?this._localFileBlobs[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this._exportType&&this._isFileProtocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(d.isC3MainWorker?a:this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),d);
a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_GetCommonRuntimeOptions(a){return{runtimeBaseUrl:this._runtimeBaseUrl,previewUrl:location.href,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),
devicePixelRatio:window.devicePixelRatio,isFullscreen:b.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:(new URLSearchParams(self.location.search)).has("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isFileProtocol:this._isFileProtocol,isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isWindowsWebView2:this.IsWindowsWebView2(),isAnyWebView2Wrapper:this.IsAnyWebView2Wrapper(),wrapperComponentIds:this._wrapperComponentIds,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,c){const d=this._GetWorkerURL(a.workerMainUrl);"preview"===this._exportType?
(this._worker=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,m)=>{const p=n=>{this._worker.removeEventListener("message",p);n.data&&"ok"===n.data.type?l():m()};this._worker.addEventListener("message",p);this._worker.postMessage({type:"construct-worker-init","import":(new URL(d,this._runtimeBaseUrl)).toString()})})):this._worker=await this.CreateWorker(d,this._runtimeBaseUrl,{type:"module",name:"Runtime",isC3MainWorker:!0});const e=document.createElement("canvas");
e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this._canvasLayers.push({canvas:e,htmlWrap:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.workerDependencyScripts||[],k=a.engineScripts;g=await Promise.all(g.map(l=>this._MaybeGetCordovaScriptURL(l)));k=await Promise.all(k.map(l=>this._MaybeGetCordovaScriptURL(l)));if("cordova"===
this._exportType)for(let l=0,m=a.projectScripts.length;l<m;++l){const p=a.projectScripts[l],n=p[0];if(n===a.mainProjectScript||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))p[1]=await this._MaybeGetCordovaScriptURL(n)}this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[c,f,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=domHandlerClasses.map(l=>new l(this));this._FindRuntimeDOMHandler();this._runtimeDomHandler._AddDefaultCanvasEventHandlers(e);this._runtimeDomHandler._AddDefaultHTMLWrapEventHandlers(h);this._runtimeDomHandler._EnableWindowResizeEvent();self.c3_callFunction=(l,m)=>this._runtimeDomHandler._InvokeFunctionFromJS(l,m);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,
c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this._canvasLayers.push({canvas:d,htmlWrap:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this._domHandlers=domHandlerClasses.map(g=>new g(this));this._FindRuntimeDOMHandler();this._runtimeDomHandler._AddDefaultCanvasEventHandlers(d);this._runtimeDomHandler._AddDefaultHTMLWrapEventHandlers(e);
e=a.engineScripts.map(g=>"string"===typeof g?(new URL(g,this._runtimeBaseUrl)).toString():g);if(Array.isArray(a.workerDependencyScripts)){var f=[...a.workerDependencyScripts].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this._MaybeGetCordovaScriptURL(g)));await Promise.all(e.map(g=>AddScript(g)));e=self.C3_ProjectScriptsStatus;f=a.mainProjectScript;const h=a.projectScripts;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this._MaybeGetCordovaScriptURL(k),
await AddScript(k),"preview"!==this._exportType||e[g]||this._ReportProjectMainScriptError(g,"main script did not run to completion")}catch(l){this._ReportProjectMainScriptError(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))k=await this._MaybeGetCordovaScriptURL(k),await AddScript(k);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions}),this._runtimeDomHandler._EnableWindowResizeEvent(),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectMainScriptError(a,c){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_OnUpdateCanvasSize(a){if(!this.IsExportingToVideo()){var c=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,htmlWrap:g}of this._canvasLayers)h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this._isFirstSizeUpdate&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this._isFirstSizeUpdate=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate;
const e=a.styleWidth+"px",f=a.styleHeight+"px",h=a.marginLeft+"px";a=a.marginTop+"px";const g=[],k=[];if(c<this._canvasLayers.length)for(;this._canvasLayers.length>c;){const {canvas:l,htmlWrap:m}=this._canvasLayers.pop();m.remove();this._useWorker&&!d?this._pendingRemoveElements.push(l):l.remove()}else if(c>this._canvasLayers.length)for(let l=0,m=c-this._canvasLayers.length;l<m;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this._useWorker?(d=c.transferControlToOffscreen(),g.push(d),
k.push(d)):g.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=h,c.style.marginTop=a,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=a,this._runtimeDomHandler._AddDefaultCanvasEventHandlers(c),this._runtimeDomHandler._AddDefaultHTMLWrapEventHandlers(d),this._canvasLayers.push({canvas:c,htmlWrap:d});for(const l of this._domHandlers)l instanceof
window.DOMElementHandler&&l._OnHTMLLayersChanged();this._UpdateHTMLElementsZOrder();return{addedCanvases:g,transferables:k}}_OnCleanUpHTMLLayers(){for(const a of this._pendingRemoveElements)a.remove();this._pendingRemoveElements.length=0}_UpdateHTMLElementsZOrder(){this._pendingUpdateHTMLZOrder||(this._pendingUpdateHTMLZOrder=!0,this._AddRAFCallback(this._updateHTMLZOrderRAFCallback))}_DoUpdateHTMLElementsZOrder(){this._RemoveRAFCallback(this._updateHTMLZOrderRAFCallback);this._pendingUpdateHTMLZOrder=
!1;let a=[];for(var c of this._domHandlers)if(c instanceof window.DOMElementHandler){var d=c._GetAllElementStatesForZOrderUpdate();d&&a.push(...d)}a.sort((h,g)=>{const k=h.GetActualHTMLIndex(),l=g.GetActualHTMLIndex();if(k!==l)return k-l;h=h.GetHTMLZIndex();g=g.GetHTMLZIndex();return h-g});let e=d=c=0,f=a.length;for(;e<f;++e){const h=a[e];h.GetActualHTMLIndex()!==c&&(this._DoUpdateHTMLElementsZOrderOnHTMLLayer(c,a.slice(d,e)),c=h.GetActualHTMLIndex(),d=e)}d<e&&this._DoUpdateHTMLElementsZOrderOnHTMLLayer(c,
a.slice(d,e))}_DoUpdateHTMLElementsZOrderOnHTMLLayer(a,c){if(!(1>=c.length||a>=this._canvasLayers.length)){c=c.map(k=>k.GetElement());var d=new Set(c);a=this.GetHTMLWrapElement(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(c.length,e.length);f<h&&c[f]===e[f];++f);for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(c[g])}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,c,d,e,f){this._messageChannelPort.postMessage({type:"event",
component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}PostToRuntimeComponentAsync(a,c,d,e,f){const h=nextResponseId++,g=new Promise((k,l)=>{pendingResponsePromises.set(h,{resolve:k,reject:l})});this._messageChannelPort.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:h},f);return g}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this._OnEventFromRuntime(a);if("result"===c)this._OnResultFromRuntime(a);else if("runtime-ready"===c)this._OnRuntimeReady();
else if("alert-error"===c)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===c)this._OnBeforeCreateRuntime();else throw Error(`unknown message '${c}'`);}_OnEventFromRuntime(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=runtimeEventHandlers.get(c))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${c}' handler '${d}':`,g);null!==f&&this._PostResultToRuntime(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this._PostResultToRuntime(f,
!0,g)).catch(g=>{console.error(`Rejection from '${c}' handler '${d}':`,g);this._PostResultToRuntime(f,!1,""+g)}):this._PostResultToRuntime(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}_PostResultToRuntime(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}_OnResultFromRuntime(a){const c=a.responseId,d=a.isOk;a=a.result;
const e=pendingResponsePromises.get(c);d?e.resolve(a):e.reject(a);pendingResponsePromises.delete(c)}AddRuntimeComponentMessageHandler(a,c,d){let e=runtimeEventHandlers.get(a);e||(e=new Map,runtimeEventHandlers.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static AddDOMHandlerClass(a){if(domHandlerClasses.includes(a))throw Error("DOM handler already added");domHandlerClasses.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===
a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||isWrapperFullscreen)}static _SetWrapperIsFullscreenFlag(a){isWrapperFullscreen=!!a}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime",
"get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.add(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){this._rafCallbacks.delete(a);0===this._rafCallbacks.size&&this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&0<this._rafCallbacks.size&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();
this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!supportedAudioFormats[a]}async _WasmDecodeWebMOpus(a){a=await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}SetIsExportingToVideo(a){this._isExportingToVideo=
!0;this._exportToVideoDuration=a}IsExportingToVideo(){return this._isExportingToVideo}GetExportToVideoDuration(){return this._exportToVideoDuration}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a){return"cordova"===this._exportType&&(a.startsWith("file:")||this._isFileProtocol&&this.IsRelativeURL(a))?(a.startsWith(this._runtimeBaseUrl)&&(a=a.substr(this._runtimeBaseUrl.length)),
a=await this.CordovaFetchLocalFileAsArrayBuffer(a),a=new Blob([a],{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const c=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(c);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(c);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");
return a}_MapPermissionID(a,c){a=a[c];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const c=this._GetPermissionAPI();return new Promise((d,e)=>c.checkPermission(this._MapPermissionID(c,a),f=>d(!!f.hasPermission),e))}_RequestPermission(a){const c=this._GetPermissionAPI();return new Promise((d,e)=>c.requestPermission(this._MapPermissionID(c,a),f=>d(!!f.hasPermission),e))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;
for(const c of a)if(!await this._HasPermission(c)&&!1===await this._RequestPermission(c))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await BlobToString(a)}_CordovaMaybeStartNextArrayBufferRead(){if(queuedArrayBufferReads.length&&
!(8<=activeArrayBufferReads)){activeArrayBufferReads++;var a=queuedArrayBufferReads.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((c,d)=>{queuedArrayBufferReads.push({filename:a,successCallback:e=>{activeArrayBufferReads--;this._CordovaMaybeStartNextArrayBufferRead();c(e)},errorCallback:e=>{activeArrayBufferReads--;this._CordovaMaybeStartNextArrayBufferRead();d(e)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,
c,d){try{const e=await this.CordovaFetchLocalFile(a),f=await BlobToArrayBuffer(e);c(f)}catch(e){d(e)}}_OnWrapperMessage(a){if("entered-fullscreen"===a)b._SetWrapperIsFullscreenFlag(!0),this._runtimeDomHandler._OnFullscreenChange();else if("exited-fullscreen"===a)b._SetWrapperIsFullscreenFlag(!1),this._runtimeDomHandler._OnFullscreenChange();else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this._wrapperInitResolve(a),this._wrapperInitResolve=null):"extension-message"===c?this.PostToRuntimeComponent("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}_OnSendWrapperExtensionMessage(a){this._SendWrapperMessage({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}_SendWrapperMessage(a){this.IsAnyWebView2Wrapper()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this._exportType&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}_SetupWebView2Polyfills(){window.moveTo=
(a,c)=>{this._SendWrapperMessage({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this._SendWrapperMessage({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}_InitWrapper(){return this.IsAnyWebView2Wrapper()?new Promise(a=>{this._wrapperInitResolve=a;this._SendWrapperMessage({type:"wrapper-init"})}):Promise.resolve()}async _ConvertDataUrisToBlobs(){const a=[];for(const [c,d]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(c,
d));await Promise.all(a)}async _ConvertDataUriToBlobs(a,c){if("object"===typeof c)this._localFileBlobs[a]=new Blob([c.str],{type:c.type}),this._localFileStrings[a]=c.str;else{let d=await this._FetchDataUri(c);d||(d=this._DataURIToBinaryBlobSync(c));this._localFileBlobs[a]=d}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(5,c);a=a.substring(c+1);c=d.split(";");d=c[0]||"";const e=c[2];a="base64"===c[1]||"base64"===e?atob(a):decodeURIComponent(a);return{mime_type:d,data:a}}_BinaryStringToBlob(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=
a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const RuntimeInterface$jscomp$1=self.RuntimeInterface;function IsCompatibilityMouseEvent(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}
const KEY_CODE_ALIASES=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),DISPATCH_RUNTIME_AND_SCRIPT={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},DISPATCH_SCRIPT_ONLY={dispatchUserScriptEvent:!0},DISPATCH_RUNTIME_ONLY={dispatchRuntimeEvent:!0};function AddStyleSheet(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function FetchImage(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function BlobToImage(b){b=URL.createObjectURL(b);try{return await FetchImage(b)}finally{URL.revokeObjectURL(b)}}function BlobToString$jscomp$1(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function BlobToSvgImage(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await BlobToImage(b);var d=await BlobToString$jscomp$1(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),h=e.getAttribute("height");if(!f.includes("%")&&!h.includes("%"))return await BlobToImage(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);
b=new Blob([d],{type:"image/svg+xml"});return await BlobToImage(b)}function IsInContentEditable(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const keyboardInputElementTagNames=new Set(["input","textarea","datalist","select"]);function IsKeyboardInputElement(b){return keyboardInputElementTagNames.has(b.tagName.toLowerCase())||IsInContentEditable(b)}const canvasOrDocTags=new Set(["canvas","body","html"]);
function PreventDefaultOnCanvasOrDoc(b){if(b.target.tagName){var a=b.target.tagName.toLowerCase();canvasOrDocTags.has(a)&&b.preventDefault()}}function PreventDefaultOnHTMLWrap(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function BlockWheelZoom(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await BlobToImage(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};
self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await BlobToSvgImage(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};let isCordovaPaused=!1;document.addEventListener("pause",()=>isCordovaPaused=!0);document.addEventListener("resume",()=>isCordovaPaused=!1);function ParentHasFocus(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}
function KeyboardIsVisible(){const b=document.activeElement;if(!b)return!1;const a=b.tagName.toLowerCase(),c=new Set("email number password search tel text url".split(" "));return"textarea"===a?!0:"input"===a?c.has(b.type.toLowerCase()||"text"):IsInContentEditable(b)}
RuntimeInterface$jscomp$1.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._enableWindowResizeEvent=!1;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._pageVisibilityIsHidden=this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._screenReaderTextWrap=document.createElement("div");this._screenReaderTextWrap.className="c3-screen-reader-text";this._screenReaderTextWrap.setAttribute("aria-live","polite");document.body.appendChild(this._screenReaderTextWrap);
this._debugHighlightElem=null;this._isExportToVideo=!1;this._exportVideoProgressMessage="";this._exportVideoUpdateTimerId=-1;this._enableAndroidVKDetection=!1;this._lastWindowWidth=b._GetWindowInnerWidth();this._lastWindowHeight=b._GetWindowInnerHeight();this._vkTranslateYOffset=this._virtualKeyboardHeight=0;b.AddRuntimeComponentMessageHandler("runtime","invoke-download",c=>this._OnInvokeDownload(c));b.AddRuntimeComponentMessageHandler("runtime","load-webfonts",c=>this._OnLoadWebFonts(c));b.AddRuntimeComponentMessageHandler("runtime",
"raster-svg-image",c=>this._OnRasterSvgImage(c));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",c=>this._OnGetSvgImageSize(c));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",c=>this._OnSetTargetOrientation(c));b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",c=>this._OnPostToDebugger(c));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",c=>this._OnPostToDebugger(c));
b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",c=>this._OnDebugHighlight(c));b.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",c=>this._OnAddStylesheet(c));
b.AddRuntimeComponentMessageHandler("runtime","script-create-worker",c=>this._OnScriptCreateWorker(c));b.AddRuntimeComponentMessageHandler("runtime","alert",c=>this._OnAlert(c));b.AddRuntimeComponentMessageHandler("runtime","screen-reader-text",c=>this._OnScreenReaderTextEvent(c));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());b.AddRuntimeComponentMessageHandler("runtime","set-exporting-to-video",c=>this._SetExportingToVideo(c));b.AddRuntimeComponentMessageHandler("runtime",
"export-to-video-progress",c=>this._OnExportVideoProgress(c));b.AddRuntimeComponentMessageHandler("runtime","exported-to-video",c=>this._OnExportedToVideo(c));b.AddRuntimeComponentMessageHandler("runtime","exported-to-image-sequence",c=>this._OnExportedToImageSequence(c));const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target,e=d.tagName.toLowerCase();a.has(e)||IsInContentEditable(d)||c.preventDefault()});window.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);
window.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);window.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc,{passive:!1});window.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc,{passive:!1});this._mousePointerLastButtons=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",BlockWheelZoom,{passive:!1});window.addEventListener("wheel",BlockWheelZoom,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());
window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",c=>this._OnFullscreenError(c));window.addEventListener("webkitfullscreenerror",c=>this._OnFullscreenError(c));window.addEventListener("mozfullscreenerror",c=>this._OnFullscreenError(c));if(b.IsiOSWebView()){if(window.visualViewport){let c=
Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{KeyboardIsVisible()||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_AddDefaultCanvasEventHandlers(b){b.addEventListener("selectstart",
PreventDefaultOnCanvasOrDoc);b.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);b.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc)}_AddDefaultHTMLWrapEventHandlers(b){b.addEventListener("selectstart",PreventDefaultOnHTMLWrap);b.addEventListener("gesturehold",PreventDefaultOnHTMLWrap);b.addEventListener("touchstart",PreventDefaultOnHTMLWrap)}_OnBeforeStartTicking(){self.setTimeout(()=>{this._enableAndroidVKDetection=!0},1E3);"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",
()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange("hidden"===document.visibilityState));this._pageVisibilityIsHidden=!("hidden"!==document.visibilityState&&!isCordovaPaused);return{isSuspended:this._pageVisibilityIsHidden}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",
{parentHasFocus:ParentHasFocus()});this._mousePointerLastButtons=0});window.addEventListener("focusin",a=>{IsKeyboardInputElement(a.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("mousedown",a=>this._OnMouseEvent("mousedown",a,DISPATCH_SCRIPT_ONLY));window.addEventListener("mousemove",a=>this._OnMouseEvent("mousemove",a,DISPATCH_SCRIPT_ONLY));
window.addEventListener("mouseup",a=>this._OnMouseEvent("mouseup",a,DISPATCH_SCRIPT_ONLY));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,DISPATCH_RUNTIME_AND_SCRIPT));window.addEventListener("wheel",a=>this._OnMouseWheelEvent("wheel",a,DISPATCH_RUNTIME_AND_SCRIPT));window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)});this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",
a=>this._OnPointerRawUpdate(a)):window.addEventListener("pointermove",a=>this._OnPointerEvent("pointermove",a));window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a));window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",a));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this._iRuntime.IsAndroid()&&!this._iRuntime.IsAndroidWebView()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this._OnAndroidVirtualKeyboardChange(this._GetWindowInnerHeight(),navigator.virtualKeyboard.boundingRect.height)}));this._iRuntime.IsiOSWebView()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}_OnAndroidVirtualKeyboardChange(b,a){document.body.style.position="";
document.body.style.overflow="";document.body.style.transform="";this._vkTranslateYOffset=0;if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-b}px)`,this._vkTranslateYOffset=b))}}_PostRuntimeEvent(b,a){this.PostToRuntime(b,a||null,DISPATCH_RUNTIME_ONLY)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_EnableWindowResizeEvent(){this._enableWindowResizeEvent=
!0;this._lastWindowWidth=this._iRuntime._GetWindowInnerWidth();this._lastWindowHeight=this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){if(!this._isExportToVideo&&this._enableWindowResizeEvent){var b=this._GetWindowInnerWidth(),a=this._GetWindowInnerHeight();if(this._iRuntime.IsAndroidWebView()){if(this._enableAndroidVKDetection){if(this._lastWindowWidth===b&&a<this._lastWindowHeight){this._virtualKeyboardHeight=this._lastWindowHeight-a;this._OnAndroidVirtualKeyboardChange(this._lastWindowHeight,
this._virtualKeyboardHeight);return}0<this._virtualKeyboardHeight&&(this._virtualKeyboardHeight=0,this._OnAndroidVirtualKeyboardChange(a,this._virtualKeyboardHeight))}this._lastWindowWidth=b;this._lastWindowHeight=a}this.PostToRuntime("window-resize",{innerWidth:b,innerHeight:a,devicePixelRatio:window.devicePixelRatio,isFullscreen:RuntimeInterface$jscomp$1.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,
a,0))}}_ScheduleSimulatedResize(b,a,c){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(b,a,c),48)}_OnSimulatedResize(b,a,c){const d=this._GetWindowInnerWidth(),e=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;d!=b||e!=a?this.PostToRuntime("window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:RuntimeInterface$jscomp$1.IsDocumentFullscreen()}):10>
c&&this._ScheduleSimulatedResize(d,e,c+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):
screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}_OnFullscreenChange(){if(!this._isExportToVideo){var b=RuntimeInterface$jscomp$1.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}}_OnFullscreenError(b){console.warn("[Construct] Fullscreen request failed: ",
b);this.PostToRuntime("fullscreenerror",{isFullscreen:RuntimeInterface$jscomp$1.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){this._pageVisibilityIsHidden!==b&&((this._pageVisibilityIsHidden=b)?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame(),this.PostToRuntime("visibilitychange",{hidden:b}),!b&&this._iRuntime.IsiOSWebView()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=
0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}_OnKeyEvent(b,a){"Backspace"===a.key&&PreventDefaultOnCanvasOrDoc(a);if(this._iRuntime.IsAnyWebView2Wrapper()){var c=["r","p","f","g","u"];(["F3","F5","F7"].includes(a.key)||a.ctrlKey&&c.includes(a.key))&&a.preventDefault()}this._isExportToVideo||(c=KEY_CODE_ALIASES.get(a.code)||a.code,this._PostToRuntimeMaybeSync(b,{code:c,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,metaKey:a.metaKey,shiftKey:a.shiftKey,
timeStamp:a.timeStamp},DISPATCH_RUNTIME_AND_SCRIPT))}_OnMouseWheelEvent(b,a,c){this._isExportToVideo||this.PostToRuntime(b,{clientX:a.clientX,clientY:a.clientY+this._vkTranslateYOffset,pageX:a.pageX,pageY:a.pageY+this._vkTranslateYOffset,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},c)}_OnMouseEvent(b,a,c){this._isExportToVideo||IsCompatibilityMouseEvent(a)||this._PostToRuntimeMaybeSync(b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY+
this._vkTranslateYOffset,pageX:a.pageX,pageY:a.pageY+this._vkTranslateYOffset,movementX:a.movementX||0,movementY:a.movementY||0,timeStamp:a.timeStamp},c)}_OnPointerEvent(b,a){if(!this._isExportToVideo){var c=0;"mouse"===a.pointerType&&(c=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY+this._vkTranslateYOffset,pageX:a.pageX,pageY:a.pageY+this._vkTranslateYOffset,
movementX:a.movementX||0,movementY:a.movementY||0,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},DISPATCH_RUNTIME_AND_SCRIPT);"mouse"===a.pointerType&&(this._mousePointerLastButtons=a.buttons)}}_OnPointerRawUpdate(b){this._OnPointerEvent("pointermove",b)}_OnTouchEvent(b,a){if(!this._isExportToVideo)for(let c=0,d=a.changedTouches.length;c<d;++c){const e=a.changedTouches[c];
this._PostToRuntimeMaybeSync(b,{pointerId:e.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:e.clientX,clientY:e.clientY+this._vkTranslateYOffset,pageX:e.pageX,pageY:e.pageY+this._vkTranslateYOffset,movementX:a.movementX||0,movementY:a.movementY||0,width:2*(e.radiusX||e.webkitRadiusX||0),height:2*(e.radiusY||e.webkitRadiusY||0),pressure:e.force||e.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:e.rotationAngle||0,timeStamp:a.timeStamp},DISPATCH_RUNTIME_AND_SCRIPT)}}_HandlePointerDownFocus(b){window!==
window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",
b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this._isExportToVideo||this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},DISPATCH_RUNTIME_AND_SCRIPT)}_OnDeviceOrientationAbsolute(b){this._isExportToVideo||
this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},DISPATCH_RUNTIME_AND_SCRIPT)}_OnDeviceMotion(b){if(!this._isExportToVideo){var a=null,c=b.acceleration;c&&(a={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var d=b.accelerationIncludingGravity;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=b.rotationRate;e&&(d={alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0});this.PostToRuntime("devicemotion",{acceleration:a,accelerationIncludingGravity:c,
rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},DISPATCH_RUNTIME_AND_SCRIPT)}}_OnInvokeDownload(b){const a=b.url;b=b.filename;const c=document.createElement("a"),d=document.body;c.textContent=b;c.href=a;c.download=b;d.appendChild(c);c.click();d.removeChild(c)}async _OnLoadWebFonts(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}async _OnRasterSvgImage(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,
b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await AddStyleSheet(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const a of b)(b=a.play())&&b.catch(c=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}TryPlayMedia(b){if("function"!==
typeof b.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(b);let a;try{a=b.play()}catch(c){this._mediaPendingPlay.add(b);return}a&&a.catch(c=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||
(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var a=this._debugHighlightElem;a.style.display="";a.style.left=b.left-1+"px";a.style.top=b.top-1+"px";a.style.width=b.width+2+"px";a.style.height=b.height+2+"px";a.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&
(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,a){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:a})}_OnScriptCreateWorker(b){const a=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:a},[a])}_OnAlert(b){alert(b.message)}_OnScreenReaderTextEvent(b){var a=b.type;"create"===a?(a=document.createElement("p"),a.id="c3-sr-"+b.id,a.textContent=b.text,this._screenReaderTextWrap.appendChild(a)):"update"===a?(a=document.getElementById("c3-sr-"+
b.id))?a.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===a?(a=document.getElementById("c3-sr-"+b.id))?a.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${a}'`)}_SetExportingToVideo(b){this._isExportToVideo=!0;const a=document.createElement("h1");a.id="exportToVideoMessage";a.textContent=b.message;document.body.prepend(a);document.body.classList.add("exportingToVideo");
this.GetRuntimeInterface().GetMainCanvas().style.display="";this._iRuntime.SetIsExportingToVideo(b.duration)}_OnExportVideoProgress(b){this._exportVideoProgressMessage=b.message;-1===this._exportVideoUpdateTimerId&&(this._exportVideoUpdateTimerId=setTimeout(()=>this._DoUpdateExportVideoProgressMessage(),250))}_DoUpdateExportVideoProgressMessage(){this._exportVideoUpdateTimerId=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=this._exportVideoProgressMessage)}_OnExportedToVideo(b){window.c3_postToMessagePort({type:"exported-video",
arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})}_OnExportedToImageSequence(b){window.c3_postToMessagePort({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})}});"use strict";
self.JobSchedulerDOM=class{constructor(b){this._runtimeInterface=b;this._baseUrl=b.GetRuntimeBaseURL();"preview"===b.GetExportType()?this._baseUrl+="workers/":this._baseUrl+=b.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}_GetWorkerScriptFolder(){return"playable-ad"===this._runtimeInterface.GetExportType()?this._runtimeInterface.GetScriptFolder():""}async Init(){if(this._hasInitialised)throw Error("already initialised");
this._hasInitialised=!0;var b=this._runtimeInterface._GetWorkerURL(this._GetWorkerScriptFolder()+"dispatchworker.js");this._dispatchWorker=await this._runtimeInterface.CreateWorker(b,this._baseUrl,{name:"DispatchWorker"});b=new MessageChannel;this._inputPort=b.port1;this._dispatchWorker.postMessage({type:"_init","in-port":b.port2},[b.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const b=this._jobWorkers.length;var a=this._runtimeInterface._GetWorkerURL(this._GetWorkerScriptFolder()+
"jobworker.js");a=await this._runtimeInterface.CreateWorker(a,this._baseUrl,{name:"JobWorker"+b});const c=new MessageChannel,d=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);a.postMessage({type:"init",number:b,"dispatch-port":c.port2,"output-port":d.port2},[c.port2,d.port2]);this._jobWorkers.push(a);return d.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,
this._outputPort]}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";function StopPropagation(b){b.stopPropagation()}
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"button")}CreateElement(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",
StopPropagation);d.addEventListener("pointermove",StopPropagation);d.addEventListener("pointerrawupdate",StopPropagation);d.addEventListener("pointerup",StopPropagation);d.addEventListener("mousedown",StopPropagation);d.addEventListener("mouseup",StopPropagation);d.addEventListener("keydown",StopPropagation);d.addEventListener("keyup",StopPropagation);d.addEventListener("contextmenu",e=>e.preventDefault());c.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",b,{isChecked:c.checked}));
a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.UpdateState(d,a);return d}_GetInputElem(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}_GetFocusElement(b){return this._GetInputElem(b)}UpdateState(b,a){const c=this._GetInputElem(b);c.checked=a.isChecked;c.disabled=!a.isEnabled;b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"touch");this.AddRuntimeMessageHandler("request-permission",a=>this._OnRequestPermission(a))}async _OnRequestPermission(b){b=b.type;let a=!0;0===b?a=await this._RequestOrientationPermission():1===b&&(a=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:b,result:a})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}});"use strict";
function StopPropagation$jscomp$1(b){b.stopPropagation()}
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"list");this.AddDOMElementMessageHandler("set-selected-index",(a,c)=>this._OnSetSelectedIndex(a,c.selectedIndex));this.AddDOMElementMessageHandler("add-item",(a,c)=>this._OnAddItem(a,c));this.AddDOMElementMessageHandler("remove-item",(a,c)=>this._OnRemoveItem(a,c));this.AddDOMElementMessageHandler("set-item",(a,c)=>this._OnSetItem(a,c));this.AddDOMElementMessageHandler("clear",a=>this._OnClear(a));
this.AddDOMElementMessageHandler("load-state",(a,c)=>this._OnLoadState(a,c))}CreateElement(b,a){const c=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const h of e)f.add(this._CreateOption(h));f.addEventListener("pointerdown",StopPropagation$jscomp$1);f.addEventListener("pointermove",StopPropagation$jscomp$1);f.addEventListener("pointerrawupdate",StopPropagation$jscomp$1);
f.addEventListener("pointerup",StopPropagation$jscomp$1);f.addEventListener("mousedown",StopPropagation$jscomp$1);f.addEventListener("mouseup",StopPropagation$jscomp$1);f.addEventListener("click",h=>{h.stopPropagation();this._PostToRuntimeElementMaybeSync("click",b,this._GetSelectionState(f))});f.addEventListener("dblclick",h=>{h.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",b,this._GetSelectionState(f))});f.addEventListener("change",()=>this.PostToRuntimeElement("change",b,this._GetSelectionState(f)));
a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.UpdateState(f,a);return f}_CreateOption(b){const a=document.createElement("option");a.text=b;return a}_GetSelectionState(b){const a=b.selectedIndex,c=[];for(let d=0,e=b.length;d<e;++d)b.options[d].selected&&c.push(d);return{selectedIndex:a,selectedIndices:c}}UpdateState(b,a){b.title=a.title;b.disabled=!a.isEnabled;b.multiple=!!a.isMultiSelect}_OnSetSelectedIndex(b,a){b.selectedIndex=a}_OnAddItem(b,a){const c=a.index;a=this._CreateOption(a.text);
0>c?b.add(a):b.add(a,c)}_OnRemoveItem(b,a){b.remove(a.index)}_OnSetItem(b,a){b.options[a.index].text=a.text}_OnClear(b){b.innerHTML=""}_OnLoadState(b,a){b.innerHTML="";for(const c of a.items)b.add(this._CreateOption(c));b.selectedIndex=a.selectedIndex;for(const c of a.selectedIndices)if(a=b.options[c])a.selected=!0}});"use strict";function StopPropagation$jscomp$2(b){b.stopPropagation()}function StopKeyPropagation(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",a=>this._OnScrollToBottom(a))}CreateElement(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",StopPropagation$jscomp$2);c.addEventListener("pointermove",StopPropagation$jscomp$2);
c.addEventListener("pointerrawupdate",StopPropagation$jscomp$2);c.addEventListener("pointerup",StopPropagation$jscomp$2);c.addEventListener("mousedown",StopPropagation$jscomp$2);c.addEventListener("mouseup",StopPropagation$jscomp$2);c.addEventListener("keydown",StopKeyPropagation);c.addEventListener("keyup",StopKeyPropagation);c.addEventListener("click",e=>{e.stopPropagation();this._PostToRuntimeElementMaybeSync("click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",
b)});c.addEventListener("input",()=>this.PostToRuntimeElement("change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.UpdateState(c,a);return c}UpdateState(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}_OnScrollToBottom(b){b.scrollTop=b.scrollHeight}});"use strict";
function StopPropagation$jscomp$3(b){b.stopPropagation()}
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"progress-bar")}CreateElement(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",StopPropagation$jscomp$3);c.addEventListener("pointermove",StopPropagation$jscomp$3);c.addEventListener("pointerrawupdate",StopPropagation$jscomp$3);c.addEventListener("pointerup",StopPropagation$jscomp$3);
c.addEventListener("mousedown",StopPropagation$jscomp$3);c.addEventListener("mouseup",StopPropagation$jscomp$3);c.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",b));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.UpdateState(c,a);return c}UpdateState(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"localstorage");this.AddRuntimeMessageHandlers([["init",()=>this._Init()],["request-persistent",()=>this._OnRequestPersistent()]])}async _Init(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}async _OnRequestPersistent(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",
b),{isOk:!1}}}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"googleplay");this.AddRuntimeMessageHandlers([["load",([a])=>this._Load(a)],["signin",()=>this._SignIn()],["signout",()=>this._SignOut()],["getplayer",()=>this._RequestPlayerDetails()],["submitscore",a=>this._SubmitScore(a)],["requestscores",a=>this._RequestHiScores(a)],["requestachievements",a=>this._RequestAchievements(a)],["requestmetadata",a=>this._RequestAchievementMetaData(a)],["reveal",a=>this._RevealAchievement(a)],
["unlock",a=>this._UnlockAchievement(a)],["increment",a=>this._IncrementAchievement(a)],["setsteps",a=>this._SetSteps(a)],["showleaderboard",a=>this._ShowLeaderboard(a)],["showachievements",a=>this._ShowAchievements(a)]]);this._playinterface=null;this._isLoaded=this._isSignedIn=!1}async _RequestPlayerDetails(){if(!this._isSignedIn)return null;const b={id:"",display:"",avatar:"",givenName:"",familyName:""};let a;a=window.cordova?await this._CallNativeAPIMethod("getPlayerData"):await this._CallWebAPIMethod("players/me");
b.id=a.playerId||"";b.display=a.displayName||"";b.avatar=a.avatarImageUrl||"";a.name&&(b.givenName=a.name.givenName||"",b.familyName=a.name.familyName||"");return b}_SignIn(){if(!this._isLoaded||this._isSignedIn)return null;this.playInterface?this.playInterface.signin():self.gapi.auth.signIn({callback:window.googlePlaySigninCallback})}_SignOut(){if(!this._isSignedIn)return null;this.playInterface?this.playInterface.signout():self.gapi.auth.signOut()}_SubmitScore(b){return this._isSignedIn?this.playInterface?
this._CallNativeAPIMethod("submitScore",b):this._CallWebAPIMethod(`leaderboards/${b.leaderboardId}/scores`,b,"post"):null}async _RequestHiScores(b){if(!this._isSignedIn)return null;const a={page:[],total:0,best:0,formattedbest:"",besttag:"",rank:0,formattedrank:""};b=this.playInterface?await this._CallNativeAPIMethod("getHiScores",b):await this._CallWebAPIMethod(`leaderboards/${b.leaderboardId}/${b.type}/${b.collection}`,b);a.total=parseInt(b.numScores,10)||0;b.playerScore&&(a.best=parseInt(b.playerScore.scoreValue,
10)||0,a.formattedbest=b.playerScore.formattedScore||"",a.besttag=b.playerScore.scoreTag||"",a.rank=parseInt(b.playerScore.scoreRank,10)||0,a.formattedrank=b.playerScore.formattedScoreRank||"");a.page=b.items;return a}async _RequestAchievements(b){const a=b.which;if(!this._isSignedIn)return null;if(this.playInterface){b=await this._CallNativeAPIMethod("getAchievements",b);const c=new Map,d=b.items;for(const e of b.items)c.set(e.id,{name:e.name,description:e.description,type:e.achievementType,totalSteps:e.totalSteps,
revealedUrl:e.revealedIconUrl,unlockedUrl:e.unlockedIconUrl});return{page:d.filter(e=>e.state===a),id:c}}return{page:(await this._CallWebAPIMethod("players/me/achievements",b)).items.filter(c=>c.state===a),id:null}}async _RequestAchievementMetaData(b){b=b.reload;if(!this._isSignedIn)return null;if(this.playInterface)return this._RequestAchievements({which:"ALL",reload:b});b=await this._CallWebAPIMethod("achievements");const a=new Map;for(const c of b.items)a.set(c.id,{name:c.name,description:c.description,
type:c.achievementType,totalSteps:c.totalSteps,revealedUrl:c.revealedIconUrl,unlockedUrl:c.unlockedIconUrl});return{page:null,id:a}}async _RevealAchievement(b){b=b.id;if(!this._isSignedIn)return null;this.playInterface?await this._CallNativeAPIMethod("revealAchievement",{achievementId:b}):await this._CallWebAPIMethod(`achievements/${b}/reveal`,null,"post");return!0}async _UnlockAchievement(b){b=b.id;if(!this._isSignedIn)return null;this.playInterface?await this._CallNativeAPIMethod("unlockAchievement",
{achievementId:b}):await this._CallWebAPIMethod(`achievements/${b}/unlock`,null,"post");return!0}async _IncrementAchievement(b){const a=b.id;b=b.steps;if(!this._isSignedIn)return null;this.playInterface?await this._CallNativeAPIMethod("incrementAchievement",{achievementId:a,numSteps:b}):await this._CallWebAPIMethod(`achievements/${a}/increment`,{stepsToIncrement:b},"post");return!0}async _SetSteps(b){const a=b.id;b=b.steps;if(!this._isSignedIn)return null;this.playInterface?await this._CallNativeAPIMethod("setStepsAchievement",
{achievementId:a,numSteps:b}):await this._CallWebAPIMethod(`achievements/${a}/setStepsAtLeast`,{steps:b},"post");return!0}_ShowLeaderboard(b){b=b.id;if(!this._isSignedIn)return null;if(this.playInterface)return null!=b?this._CallNativeAPIMethod("showLeaderboard",{leaderboardId:b}):this._CallNativeAPIMethod("showLeaderboards");throw Error("not available");}_ShowAchievements(){if(!this._isSignedIn)return null;if(this.playInterface)return this._CallNativeAPIMethod("showAchievements");throw Error("not available");
}_CallWebAPIMethod(b,a,c="get"){return new Promise((d,e)=>{self.gapi.client.request({path:"/games/v1/"+b,method:c,params:a,callback:function(f){let h=f?f.error:"no_response";h?("object"===typeof h?h="string"===typeof h.message?h.message:"unknown":"string"!==typeof h&&(h="unknown"),e(h)):d(f)}})})}_CallNativeAPIMethod(b,a={}){return new Promise((c,d)=>{this.playInterface[b](a,(e,f)=>{e?d(e):c(f)})})}_Load(b){return new Promise((a,c)=>{const d=(e,f)=>{this._isSignedIn=f;this.PostToRuntime("login",{state:f,
error:e})};window.cordova?this._LoadCordovaAPI(a,c,d):this._LoadWebAPI(b,a,c,d)})}_LoadWebAPI(b,a,c,d){const e=(f,h)=>{const g=document.createElement("meta");g.setAttribute("name","google-signin-"+f);g.setAttribute("content",h);document.head.appendChild(g)};window.googlePlayLoadCallback=(...f)=>{this._isLoaded=!0;a(...f)};window.googlePlaySigninCallback=f=>{f.status&&f.status.signed_in?d("",!0):d(f.error+"",!1)};e("clientid",b);e("cookiepolicy","single_host_origin");e("callback","googlePlaySigninCallback");
e("scope","https://www.googleapis.com/auth/games");b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("async","");b.setAttribute("src","https://apis.google.com/js/client.js?onload=googlePlayLoadCallback");b.addEventListener("error",()=>c("failed to load script"));document.head.appendChild(b)}_LoadCordovaAPI(b,a,c){const d=window.cordova.plugins.ConstructPlayGames;if(d)this.playInterface=d,b(),this._isLoaded=!0;else return a();d.setCallback(c);d.silentSignIn()}});
